return {
    "folke/snacks.nvim",
    priority = 1000,
    lazy = false,
    ---@type snacks.Config

    opts = {
        animate = { enabled = false },
        bigfile = { enabled = true },
        bufdelete = { enabled = true },
        dashboard = { enabled = false },
        debug = { enabled = false },
        dim = { enabled = false },
        git = { enabled = false },
        gitbrowse = { enabled = false },
        health = { enabled = true },
        indent = {
            enabled = true,
            animate = {
                enabled = false,
            }
        },
        input = { enabled = true },
        layout = { enabled = false },
        lazygit = { enabled = true },
        meta = { enabled = false },
        notifier = { enabled = true },
        notify = { enabled = true },
        picker = { enabled = true },
        profiler = { enabled = false },
        quickfile = { enabled = false },
        rename = { enabled = false },
        scope = { enabled = false },
        scratch = { enabled = false },
        scroll = { enabled = false },
        statuscolumn = {
            enabled = true,
            left = { "sign", "mark" },
        },
        terminal = { enabled = false },
        toggle = { enabled = false },
        util = { enabled = true },
        win = { enabled = false },
        words = { enabled = false },
        zen = { enabled = false, },

    },
    keys = {
        { "<leader>o",  function() Snacks.picker.buffers() end,         desc = "Buffers" },
        { "<leader>f",  function() Snacks.picker.files() end,           desc = "Find Files" },
        { "<leader>r",  function() Snacks.picker.grep() end,            desc = "Grep" },
        { "<leader>Fr",  function() Snacks.picker.recent() end,          desc = "Recent" },
        { "<leader>Fgf", function() Snacks.picker.git_files() end,       desc = "Git Files" },
        { "<leader>Fgl", function() Snacks.picker.git_log() end,         desc = "Git Log" },
        { "<leader>Fgs", function() Snacks.picker.git_status() end,      desc = "Git Status" },
        { "<leader>Fl",  function() Snacks.picker.lines() end,           desc = "Buffer Lines" },
        { "<leader>Fb",  function() Snacks.picker.grep_buffers() end,    desc = "Grep Open Buffers" },
        { "<leader>Fw",  function() Snacks.picker.grep_word() end,       desc = "Visual selection or word", mode = { "n", "x" } },
        { "<leader>FC",  function() Snacks.picker.command_history() end, desc = "Command History" },
        { "<leader>Fc",  function() Snacks.picker.commands() end,        desc = "Commands" },
        { "<leader>Fd",  function() Snacks.picker.diagnostics() end,     desc = "Diagnostics" },
        { "<leader>Fh",  function() Snacks.picker.help() end,            desc = "Help Pages" },
        { "<leader>Fj",  function() Snacks.picker.jumps() end,           desc = "Jumps" },
        { "<leader>Fk",  function() Snacks.picker.keymaps() end,         desc = "Keymaps" },
        { "<leader>Fq",  function() Snacks.picker.qflist() end,          desc = "Quickfix List" },
        { "<leader>FS",  function() Snacks.picker.lsp_symbols() end,     desc = "LSP Symbols" },

        { "<leader>Fn",  function() Snacks.notifier.show_history() end,  desc = "Notification History" },
        { "<leader>gl",  function() Snacks.lazygit() end,                desc = "Lazygit" },
        { "<leader>nn",  function() Snacks.notifier.hide() end,          desc = "Dismiss All Notifications" },
    }
}
