theme = "tokyonight"

[editor]
bufferline = "always"
line-number = "relative"
mouse = false
end-of-line-diagnostics = "hint"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.inline-diagnostics]
cursor-line = "error"

[keys.normal]
C-s = ":w"

"'" = "save_selection"

C-g = [
    ":write-all", 
    ":new", 
    ":insert-output lazygit", 
    ":set mouse false", # First disable mouse to hint helix into activating it
    ":set mouse true",
    ":buffer-close!", 
    ":redraw", 
    ":reload-all"
]

C-y = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi %{buffer_name} --chooser-file=/tmp/unique-file',
  ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
]
